/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Calendar: typeof import('./../../src/components/Calendar.vue')['default']
    ContentCard: typeof import('./../../src/components/ContentCard.vue')['default']
    IGgAdd: typeof import('~icons/gg/add')['default']
    IMdiPlus: typeof import('~icons/mdi/plus')['default']
    IMdiPlusOutline: typeof import('~icons/mdi/plus-outline')['default']
    InicioOperaciones: typeof import('./../../src/components/Pages/InicioOperaciones.vue')['default']
    InicioSeguridad: typeof import('./../../src/components/Pages/InicioSeguridad.vue')['default']
    InicioServicio: typeof import('./../../src/components/Pages/InicioServicio.vue')['default']
    PageTemplate: typeof import('./../../src/components/Pages/PageTemplate.vue')['default']
    PageView: typeof import('./../../src/components/View/PageView.vue')['default']
    RootView: typeof import('./../../src/components/View/RootView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SuspenseView: typeof import('./../../src/components/View/SuspenseView.vue')['default']
    TransitionView: typeof import('./../../src/components/View/TransitionView.vue')['default']
  }
}
